@extends('layouts.three-columns')

@section('title')
@endsection

@section('head')
	<meta name="_token" content="{{ csrf_token() }}">
@endsection


@section('leftColumn')
	@include('includes.conversations-nav', ['conversations' => $conversations])
@endsection

<?php
	if($c->is_group_chat){
		$conversation_title = "group chat FOOBAR";
	}else{
		if($c->participants[0] == Auth::user()){
			$recipient = $c->participants[1];
		}else{
			$recipient = $c->participants[0];
		}
		$conversation_title = $recipient->username;
	}
?>


@section('centerColumn')
	<div id="conversation-container">
	    <div id="conv-header">
	    	<h2>{{$conversation_title}}</h2>
	    </div>
	    <div id="conv-body">
	    	<!-- the content inside this div is generated by an AJAX response -->
	    </div>
	    <div id="conv-footer">
	    	<form id="sendMsgForm" action="">
  				<input type="hidden" id="convId" value="{{$c->id}}">
		      <div class="input-group mb-3">
		        <textarea class="control-form" id="conversation-textarea" placeholder="Message..." spellcheck="false"></textarea>
		        <div class="input-group-append">
		          <button type="submit" class="btn btn-primary">Send</button>
		        </div>
		      </div>
	      </form>
	    </div>
	</div>
@endsection


@section('rightColumn')
@endsection



@section('jsBottom')
<script type="text/javascript">

	$('body').on('keydown input', '#conversation-textarea', function() {
		this.style.removeProperty('height');
		this.style.height = (this.scrollHeight+2) + 'px';
	});

	$(document).ready(function() {
		fetchAndRenderPrevMsgs(10);

		// by default, scroll to the very bottom of conversation upon load
		var myDiv = document.getElementById('conv-body');
		myDiv.scrollTop = myDiv.scrollHeight;
	});

	function fetchAndRenderPrevMsgs(n) {
		var myDiv = document.getElementById('conv-body');
		var oldHeight = myDiv.scrollHeight;
  		$.ajax({
  			type: "GET",
  			url: "/fetch-prev-n-messages-of-conversation",
  			data: {
  				n: n,
  				conversationId: {{$c->id}}
  			},
  			success: function(response) {
          		// prepend data to the div
  				myDiv.innerHTML = response + myDiv.innerHTML;
  			},
  			error: function(response) {
  				console.log(response);
  			},
  			complete: function(response) {
  				var newHeight = myDiv.scrollHeight;
  				myDiv.scrollTop = newHeight - oldHeight;
  			}
  		});
	}

	$('#conv-body').on('scroll', function() {
		if($(this).scrollTop() == 0){
			fetchAndRenderPrevMsgs(10);
		}
	});

	$('#sendMsgForm').on('submit', function(e){
		e.preventDefault();
		var convId = $('#convId').val();
		var msg = $('#conversation-textarea').val();
		$.ajax({
			type: "POST",
			url: "/send-msg",
			data: {
				convId: convId,
				msg: msg,
				_token: "{{csrf_token()}}"
			},
			success: function(response) {
				console.log(response);
			},
			error: function(response) {
				console.log(response);
			}
		});
	});

</script>
@endsection