@extends('layouts.three-columns')

@section('title')
@endsection

@section('head')
	<meta name="_token" content="{{ csrf_token() }}">
@endsection


@section('leftColumn')
	@include('includes.conversations-nav', ['conversations' => $conversations])
@endsection

<?php
	if($c->is_group_chat){
		$conversation_title = "group chat FOOBAR";
	}else{
		if($c->participants[0] == Auth::user()){
			$recipient = $c->participants[1];
		}else{
			$recipient = $c->participants[0];
		}
		$conversation_title = $recipient->username;
	}
?>


@section('centerColumn')
	<div id="conversation-container">
	    <div id="conv-header">
	    	<h2>{{$conversation_title}}</h2>
	    </div>
	    <div id="conv-body">


	    	<!-- content generated by AJAX response -->




	    </div>
	    <div id="conv-footer">
	      <div class="input-group mb-3">
	        <textarea class="control-form" id="conversation-textarea"></textarea>
	        <div class="input-group-append">
	          <button class="btn btn-primary" type="button">Send</button>
	        </div>
	      </div>
	    </div>
	</div>
@endsection


@section('rightColumn')
@endsection



@section('jsBottom')
<script type="text/javascript">

	$('body').on('keydown input', '#conversation-textarea', function() {
		this.style.removeProperty('height');
		this.style.height = (this.scrollHeight+2) + 'px';
	});

	$(document).ready(function() {
		fetchAndRenderPrevMsgs(10);

		// by default, scroll to the very bottom of conversation upon load
		var myDiv = document.getElementById('conv-body');
		myDiv.scrollTop = myDiv.scrollHeight;
	});

	function fetchAndRenderPrevMsgs(n) {
		var myDiv = document.getElementById('conv-body');
		var oldHeight = myDiv.scrollHeight;
  		$.ajax({
  			type: "GET",
  			url: "/fetch-prev-n-messages-of-conversation",
  			data: {
  				n: n,
  				conversationId: {{$c->id}}
  			},
  			success: function(response) {
          		// prepend data to the div
  				myDiv.innerHTML = response + myDiv.innerHTML;
  			},
  			error: function(response) {
  				console.log(response);
  			},
  			complete: function(response) {
  				var newHeight = myDiv.scrollHeight;
  				myDiv.scrollTop = newHeight - oldHeight;
  			}
  		});
	}

	$('#conv-body').on('scroll', function() {
		if($(this).scrollTop() == 0){
			fetchAndRenderPrevMsgs(10);
		}
	});
</script>
@endsection